In [1]:
import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
import os
import time

print("akbaaarr")
input("click enter to continue")
os.system("clear")
print("tunggu ya...")
time.sleep(2)
os.system("clear")
print("alfiiiinnnn")

akbaaarr


click enter to continue 


tunggu ya...
alfiiiinnnn


In [13]:
import os, time, numpy as np, random

# print("akbaaarr")
# input("click enter to continue")
# os.system("clear")
# print("tunggu ya...")
# time.sleep(2)
# os.system("clear")
# print("alfiiiinnnn")

# 1dimensi
data = np.array([1,2,3,4,5,6])
print(type(data))

# 2dimensi
arr = np.array([[1, 2, 3], [4, 5, 6],[3,4,3]])
print("first row:",arr[0])
print("jumlah:",arr[0,1] + arr[1,0])

# untuk membaca array
for i in arr:
    for y in i:
        print(y)

# slice array
data_slice = data[:5]
print("data yang telah di slice:",data_slice)

# cek tipe data yang disimpan di dalam array itu:
print(arr.dtype)


# copy and view data:
x = arr.copy()
x[0,1] = 100
print("sebelum:",arr)
print("setelah:",x)


# shape:
print(arr.shape)

# reshaping:
new_arr = data.reshape(2,3)
print("data reshaping:",new_arr)


# menghitung maksimal:
print(arr.max())
print(arr.min())

# standart deviasi:
print(arr.std())

# mean
print(arr.mean())

# cara buat data random
data_random = np.random.randint(50,100, size= 10)
print("data yang didapatkan secara random:",data_random)
print(data_random.max())

# sort
print(np.sort(data_random))

# search data in numpy array
search = np.where(arr == 3)
print("ada di nomor indeks:",search)


# for i in data:
#     print(i)a elubel"

<class 'numpy.ndarray'>
first row: [1 2 3]
jumlah: 6
1
2
3
4
5
6
3
4
3
data yang telah di slice: [1 2 3 4 5]
int64
sebelum: [[1 2 3]
 [4 5 6]
 [3 4 3]]
setelah: [[  1 100   3]
 [  4   5   6]
 [  3   4   3]]
(3, 3)
data reshaping: [[1 2 3]
 [4 5 6]]
6
1
1.4229164972072998
3.4444444444444446
data yang didapatkan secara random: [97 94 97 75 59 92 52 54 63 64]
97
[52 54 59 63 64 75 92 94 97 97]
ada di nomor indeks: (array([0, 2, 2]), array([2, 0, 2]))


In [85]:
#INI ADALAH BAGIAN PROJECT
import numpy as np, random

hari = ['SENIN','SELASA','RABU','KAMIS','JUMAT','SABTU','MINGGU','NO']
bacaan = []
p = [1,2,3,4,5,6,7]

def perhari ():
    global H
    print(bacaan[H].tolist())

def hitung ():
    global H
    print(bacaan[s].max())
    print(bacaan[s].min())
    print(bacaan[s].mean(),'\n')

for i in p:
    suhu = np.random.randint(20,30, size=5)
    bacaan.append(suhu[0:5])
while True:    
    H = int(input('SUHU PADA HARI APA YANG INGIN DILIHAT?\n1. Senin\n2. Selasa\n3. Rabu\n4. Kamis\n5. Jumat\n6. Sabtu\n7. Minggu\n8. SELESAI\n Masukkan pilihan anda di sini(nomor)'))
    H -= 1

    if H < 0 or H > 7:
        print('invalid, coba lagi')
    elif H == 7:
        break
    else:
        print(hari[H],'dengan:')
        perhari()
        hitung()
    


SUHU PADA HARI APA YANG INGIN DILIHAT?
1. Senin
2. Selasa
3. Rabu
4. Kamis
5. Jumat
6. Sabtu
7. Minggu
8. SELESAI
 Masukkan pilihan anda di sini(nomor) 1


SENIN dengan:
[27, 23, 21, 25, 22]
27
21
23.6 



SUHU PADA HARI APA YANG INGIN DILIHAT?
1. Senin
2. Selasa
3. Rabu
4. Kamis
5. Jumat
6. Sabtu
7. Minggu
8. SELESAI
 Masukkan pilihan anda di sini(nomor) 8


In [86]:
import numpy as np, matplotlib.pyplot as plt

x =  #start, end, increament
y = 

[0 1 2 3 4 5 6 7 8 9]
